[package]
name = "frequenz-microgrid-component-graph-python-bindings"
version = "0.5.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "frequenz_microgrid_component_graph_python_bindings"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.29.0"
frequenz-microgrid-component-graph = "0.6.0"
